script:
  - make CXX=clang++-6.0 swob.o
  - make clean
  - make CXX=g++-8
  - cppcheck --enable=all .
  - bash <(curl -s https://codecov.io/bash)
  - llvm-cov-6.0 --version

deploy:
  provider: pages
  github-token: ${api_key}
  skip-cleanup: true
  on:
    branch: master

matrix:
  include:
    - os: linux
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang++-6.0
            - g++-8
            - cppcheck
            - gnuplot
