script: clang++ --version && make
deploy:
  provider: pages
  github-token: ${api_key}
  skip-cleanup: true
  keep-history: true
  on:
    branch: master

matrix:
  include:
    - os: linux
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang++-6.0
            - g++-8
            - cppcheck
            - cowsay
