script: make
deploy:
  provider: pages
  github-token: ${api_key}
  skip-cleanup: true
  keep-history: true
  on:
    branch: master

addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages: cowsay
